// Copyright (c) 2014 Jiho Choi. All rights reserved.
// To use this source, see LICENSE file.

#include "core_first.h"
#include "profiler.cc"
#include "run_length_compress.cc"
#include "thread.cc"
#include "guid.cc"
#include "blob.cc"
#include "chunk.cc"
#include "file_chunk.cc"
#include "package_chunk.cc"
#include "command_line.cc"
#include "config.cc"
#include "error.cc"
#include "file.cc"
#include "file_path.cc"
#include "frame_timer.cc"
#include "ini_file.cc"
#include "json.cc"
#include "logger.cc"
#include "math.cc"
#include "name.cc"
#include "name_pool.cc"
#include "os.cc"
#include "resource_path.cc"
#include "resource.cc"
#include "resource_manager.cc"
#include "package.cc"
#include "string.cc"
#include "string_util.cc"
#include "string_stream.cc"
#include "transform.cc"
#include "util.cc"
#include "memory_pool.cc"
#include "core_main.cc"

#if defined(DG_TARGET_WIN32)
#include "profiler_win32.cc"
#include "interlocked_win32.cc"
#include "thread_win32.cc"
#include "guid_win32.cc"
#include "command_line_win32.cc"
#include "critical_section_win32.cc"
#include "leak_detector_win32.cc"
#include "date_time_win32.cc"
#include "file_win32.cc"
#include "ini_file_win32.cc"
#include "console_win32.cc"
#include "os_win32.cc"
#include "timer_win32.cc"
#elif defined(DG_TARGET_ANDROID)
#include "file_pure.cc"
#include "ini_file_pure.cc"
#include "console_pure.cc"
#include "date_time_pure.cc"
#include "os_android.cc"
#include "timer_android.cc"
#include "critical_section_pthread.cc"
#include "guid_pure.cc"
#include "thread_pthread.cc"
#include "interlocked_android.cc"
#include "ini_file_handler.cc"
#endif

#if defined(DG_RENDERER_DX9)
#include "math_dx9.cc"
#else
#include "math_pure.cc"
#endif
